package com.saad.main;

import com.saad.VisitorComponents.VisitorFrame;
import com.saad.GlobalComponents.HeadPanel;
import com.saad.swing.PanelBorder;
import java.awt.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author saadk
 */
public class main extends JFrame {

    /**
     * Creates new form FirstFrame
     */
    public main() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
         headPanel1.initMoving(main.this); 
                 img.setSize(658,768);
        
Icon originalIcon = img.getIcon();
int iconWidth = originalIcon.getIconWidth();
int iconHeight = originalIcon.getIconHeight();
Image scaledImage = new BufferedImage(iconWidth, iconHeight, BufferedImage.TYPE_INT_ARGB);
Graphics2D graphics = (Graphics2D) scaledImage.getGraphics();
originalIcon.paintIcon(img, graphics, 0, 0);
graphics.dispose();
scaledImage = scaledImage.getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH);
img.setIcon(new ImageIcon(scaledImage));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        headPanel1 = new com.saad.GlobalComponents.HeadPanel();
        CardPanel = new javax.swing.JPanel();
        welcomeFrame1 = new com.saad.swing.WelcomeFrame();
        welcomeLoginFrame1 = new com.saad.swing.WelcomeLoginFrame();
        welcomeSignupFrame1 = new com.saad.swing.WelcomeSignupFrame();
        img = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(71, 71, 71));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1300, 768));
        setUndecorated(true);

        headPanel1.setPreferredSize(new java.awt.Dimension(1300, 50));

        CardPanel.setBackground(new java.awt.Color(0, 0, 0));
        CardPanel.setMaximumSize(new java.awt.Dimension(650, 2147483647));
        CardPanel.setMinimumSize(new java.awt.Dimension(650, 769));
        CardPanel.setOpaque(false);
        CardPanel.setPreferredSize(new java.awt.Dimension(650, 769));
        CardPanel.setLayout(new java.awt.CardLayout());
        CardPanel.add(welcomeFrame1, "card2");
        CardPanel.add(welcomeLoginFrame1, "card3");
        CardPanel.add(welcomeSignupFrame1, "card4");

        CardPanel.setBackground(new Color(0, 0, 0, 0)); // set the background to transparent

        img.setIcon(new javax.swing.ImageIcon("C:\\Users\\saadk\\OneDrive\\Desktop\\app_wp.PNG")); // NOI18N
        img.setText(" ");
        img.setMaximumSize(new java.awt.Dimension(600, 768));
        img.setMinimumSize(new java.awt.Dimension(600, 768));
        img.setPreferredSize(new java.awt.Dimension(600, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(img, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(CardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public JPanel getWelcomeFrame() {
    return welcomeFrame1;
}
    public JPanel getWelcomeLoginFrame() {
    return welcomeLoginFrame1;
}
    public JPanel getWelcomeSignupFrame() {
    return welcomeSignupFrame1;
    }
    public JPanel getCardPanel() {
    return CardPanel;
}
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel CardPanel;
    private com.saad.GlobalComponents.HeadPanel headPanel1;
    private javax.swing.JLabel img;
    private javax.swing.JRadioButton jRadioButton1;
    private com.saad.swing.WelcomeFrame welcomeFrame1;
    private com.saad.swing.WelcomeLoginFrame welcomeLoginFrame1;
    private com.saad.swing.WelcomeSignupFrame welcomeSignupFrame1;
    // End of variables declaration//GEN-END:variables
}
