/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.saad.ClientComponents;

import com.saad.Classes.Account;
import static com.saad.Classes.Account.findAccount;
import com.saad.Classes.DBConnection;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JPasswordField;

/**
 *
 * @author saadk
 */
public class ClientAccountFrame extends javax.swing.JPanel {

    private Object com;

    /**
     * Creates new form AdminCarFrame
     */
    public ClientAccountFrame() {
        initComponents();
                 setOpaque(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        delacc = new javax.swing.JButton();

        setBackground(new java.awt.Color(178, 178, 178));
        setForeground(new java.awt.Color(226, 226, 226));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("First name :");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Last name :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Email :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Password :");

        FirstName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FirstName.setForeground(new java.awt.Color(51, 51, 51));

        LastName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(51, 51, 51));

        Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(51, 51, 51));

        Password.setBackground(new java.awt.Color(178, 178, 178));
        Password.setForeground(new java.awt.Color(51, 51, 51));
        Password.setBorder(null);
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PasswordMouseExited(evt);
            }
        });

        delacc.setBackground(new java.awt.Color(255, 204, 204));
        delacc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        delacc.setForeground(new java.awt.Color(0, 0, 0));
        delacc.setText("Delete Account");
        delacc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delaccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delaccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delaccMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                .addComponent(delacc, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(delacc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseEntered
    JPasswordField passwordField = (JPasswordField) evt.getSource();
    passwordField.setEchoChar((char) 0);
    }//GEN-LAST:event_PasswordMouseEntered

    private void PasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseExited
    JPasswordField passwordField = (JPasswordField) evt.getSource();
    passwordField.setEchoChar('*');    }//GEN-LAST:event_PasswordMouseExited

    private void delaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delaccMouseClicked

            int id = Integer.parseInt(ClientFrame.Menu.Id_Account.getText());

        // Find the account
        Account account = findAccount(id);

        // If account is found, add a row to the "accountdeletion" table
        if (account != null) {
            try {
                Connection connection = DBConnection.getConnection();
                String req = "INSERT INTO accountdeletion (id_ACCOUNT, first_name, last_name, email) VALUES (?, ?, ?, ?)";
                PreparedStatement ps = connection.prepareStatement(req);
                ps.setInt(1, account.Id);
                ps.setString(2, account.FirstName);
                ps.setString(3, account.LastName);
                ps.setString(4, account.Email);
                ps.executeUpdate();

                deletionRequest dr = new deletionRequest();
                dr.setVisible(true);
            } catch (SQLException ex) {
                ex.printStackTrace();
                // Display an error message
            }
        } 
    }//GEN-LAST:event_delaccMouseClicked

    private void delaccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delaccMouseEntered
            delacc.setBackground(Color.decode("#FF6666"));
    }//GEN-LAST:event_delaccMouseEntered

    private void delaccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delaccMouseExited
            delacc.setBackground(Color.decode("#FFCCCC"));
    }//GEN-LAST:event_delaccMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Email;
    public static javax.swing.JLabel FirstName;
    public static javax.swing.JLabel LastName;
    public static javax.swing.JPasswordField Password;
    private javax.swing.JButton delacc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
