/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.saad.ClientComponents;

import com.saad.Classes.Account;
import com.saad.Classes.Car;
import com.saad.VisitorComponents.VisitorFrame;
import com.saad.main.main;
import com.saad.swing.WelcomeFrame;
import com.saad.swing.WelcomeLoginFrame;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author saadk
 */
public class ClientMenuItem extends javax.swing.JPanel {

    /**
     * Creates new form ClientMenuItem
     */
    public ClientMenuItem() {
        initComponents();
        setOpaque(false);

    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogOutButton = new javax.swing.JButton();
        Account = new javax.swing.JButton();
        FormButton = new javax.swing.JButton();
        Notifications = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        comment = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        setToolTipText("");

        LogOutButton.setBackground(new java.awt.Color(0, 0, 0));
        LogOutButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        LogOutButton.setForeground(new java.awt.Color(173, 173, 173));
        LogOutButton.setText("Log out");
        LogOutButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        LogOutButton.setContentAreaFilled(false);
        LogOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOutButton.setFocusPainted(false);
        LogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseExited(evt);
            }
        });

        Account.setBackground(new java.awt.Color(0, 0, 0));
        Account.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        Account.setForeground(new java.awt.Color(173, 173, 173));
        Account.setText("Account");
        Account.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        Account.setContentAreaFilled(false);
        Account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Account.setFocusPainted(false);
        Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccountMouseExited(evt);
            }
        });

        FormButton.setBackground(new java.awt.Color(0, 0, 0));
        FormButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        FormButton.setForeground(new java.awt.Color(173, 173, 173));
        FormButton.setText("Cars");
        FormButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        FormButton.setContentAreaFilled(false);
        FormButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FormButton.setFocusPainted(false);
        FormButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FormButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FormButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FormButtonMouseExited(evt);
            }
        });

        Notifications.setBackground(new java.awt.Color(0, 0, 0));
        Notifications.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        Notifications.setForeground(new java.awt.Color(173, 173, 173));
        Notifications.setText("Notifications");
        Notifications.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        Notifications.setContentAreaFilled(false);
        Notifications.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Notifications.setFocusPainted(false);
        Notifications.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NotificationsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NotificationsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NotificationsMouseExited(evt);
            }
        });

        jLabel2.setText(" ");

        n.setBackground(new java.awt.Color(204, 0, 0));
        n.setText(" ");
        n.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        n.setMaximumSize(new java.awt.Dimension(225, 5));
        n.setMinimumSize(new java.awt.Dimension(5, 5));
        n.setOpaque(true);
        n.setPreferredSize(new java.awt.Dimension(202, 10));
        n.setVisible(false);

        comment.setBackground(new java.awt.Color(0, 0, 0));
        comment.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        comment.setForeground(new java.awt.Color(173, 173, 173));
        comment.setText("Comments");
        comment.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        comment.setContentAreaFilled(false);
        comment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comment.setFocusPainted(false);
        comment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                commentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                commentMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Account, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(Notifications, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addComponent(FormButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogOutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(FormButton)
                .addGap(75, 75, 75)
                .addComponent(Account)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Notifications)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(comment)
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(LogOutButton)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseClicked
        
            ClientFrame clientFrame = (ClientFrame) SwingUtilities.getWindowAncestor(this);
            clientFrame.setVisible(false);
            
            main m= new main();
            m.setVisible(true);
            
    }//GEN-LAST:event_LogOutButtonMouseClicked

    private void LogOutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseEntered
            LogOutButton.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_LogOutButtonMouseEntered

    private void LogOutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseExited
            LogOutButton.setBackground(null);
            LogOutButton.setForeground(Color.decode("#ADADAD"));
    }//GEN-LAST:event_LogOutButtonMouseExited

    private void AccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseClicked
        ClientFrame clientFrame = (ClientFrame) SwingUtilities.getWindowAncestor(this);

        // Get the CardLayout from the main JPanel
        CardLayout cardLayout = (CardLayout) clientFrame.getClientCardPanel().getLayout();

        // Get the panels by their names
        JPanel clientAccountFrame1 = clientFrame.getclientAccountFrame1();
        JPanel clientCarFrameSP1 = clientFrame.getclientCarFrameSP1();
        JPanel clientResFrameSP1 = clientFrame.getclientResFrameSP1();
        JPanel commentSP1 = clientFrame.getcommentSP1();
        JPanel notifFrameSP1 = clientFrame.getnotifFrameSP1();

        // Set the visibility of the panels based on their names
        cardLayout.show(clientFrame.getClientCardPanel(), "clientFrame");
        clientAccountFrame1.setVisible(false);
        clientCarFrameSP1.setVisible(false);
        clientResFrameSP1.setVisible(true);
        commentSP1.setVisible(false);    
        notifFrameSP1.setVisible(false);    
        
    }//GEN-LAST:event_AccountMouseClicked

    private void AccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseExited
            Account.setBackground(null);
            Account.setForeground(Color.decode("#ADADAD"));
    }//GEN-LAST:event_AccountMouseExited

    private void AccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountMouseEntered
            Account.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_AccountMouseEntered

    private void FormButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FormButtonMouseEntered
            FormButton.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_FormButtonMouseEntered

    private void FormButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FormButtonMouseClicked

        ClientFrame clientFrame = (ClientFrame) SwingUtilities.getWindowAncestor(this);

        // Get the CardLayout from the main JPanel
        CardLayout cardLayout = (CardLayout) clientFrame.getClientCardPanel().getLayout();

        // Get the panels by their names
        JPanel clientAccountFrame1 = clientFrame.getclientAccountFrame1();
        JPanel clientCarFrameSP1 = clientFrame.getclientCarFrameSP1();
        JPanel clientResFrameSP1 = clientFrame.getclientResFrameSP1();
        JPanel commentSP1 = clientFrame.getcommentSP1();
        JPanel notifFrameSP1 = clientFrame.getnotifFrameSP1();

        // Set the visibility of the panels based on their names
        cardLayout.show(clientFrame.getClientCardPanel(), "clientFrame");
        clientAccountFrame1.setVisible(false);
        clientCarFrameSP1.setVisible(true);
        clientResFrameSP1.setVisible(false);
        commentSP1.setVisible(false);    
        notifFrameSP1.setVisible(false);    

    }//GEN-LAST:event_FormButtonMouseClicked

    private void NotificationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotificationsMouseClicked
        ClientFrame clientFrame = (ClientFrame) SwingUtilities.getWindowAncestor(this);

        // Get the CardLayout from the main JPanel
        CardLayout cardLayout = (CardLayout) clientFrame.getClientCardPanel().getLayout();

        // Get the panels by their names
        JPanel clientAccountFrame1 = clientFrame.getclientAccountFrame1();
        JPanel clientCarFrameSP1 = clientFrame.getclientCarFrameSP1();
        JPanel clientResFrameSP1 = clientFrame.getclientResFrameSP1();
        JPanel notifFrameSP1 = clientFrame.getnotifFrameSP1();
        JPanel commentSP1 = clientFrame.getcommentSP1();

        // Set the visibility of the panels based on their names
        cardLayout.show(clientFrame.getClientCardPanel(), "clientFrame");
        clientAccountFrame1.setVisible(false);
        clientCarFrameSP1.setVisible(false);
        clientResFrameSP1.setVisible(false);
        notifFrameSP1.setVisible(true);         
        commentSP1.setVisible(false);    

    }//GEN-LAST:event_NotificationsMouseClicked

    private void NotificationsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotificationsMouseEntered
            Notifications.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_NotificationsMouseEntered

    private void commentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMouseClicked

        ClientFrame clientFrame = (ClientFrame) SwingUtilities.getWindowAncestor(this);

        // Get the CardLayout from the main JPanel
        CardLayout cardLayout = (CardLayout) clientFrame.getClientCardPanel().getLayout();

        // Get the panels by their names
        JPanel clientAccountFrame1 = clientFrame.getclientAccountFrame1();
        JPanel clientCarFrameSP1 = clientFrame.getclientCarFrameSP1();
        JPanel clientResFrameSP1 = clientFrame.getclientResFrameSP1();
        JPanel notifFrameSP1 = clientFrame.getnotifFrameSP1();
        JPanel commentSP1 = clientFrame.getcommentSP1();

        // Set the visibility of the panels based on their names
        cardLayout.show(clientFrame.getClientCardPanel(), "clientFrame");
        clientAccountFrame1.setVisible(false);
        clientCarFrameSP1.setVisible(false);
        clientResFrameSP1.setVisible(false);
        notifFrameSP1.setVisible(false);    
        commentSP1.setVisible(true);    

    }//GEN-LAST:event_commentMouseClicked

    private void commentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMouseEntered
            comment.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_commentMouseEntered

    private void commentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMouseExited
                   comment.setBackground(null);
            comment.setForeground(Color.decode("#ADADAD"));      }//GEN-LAST:event_commentMouseExited

    private void FormButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FormButtonMouseExited
                   FormButton.setBackground(null);
            FormButton.setForeground(Color.decode("#ADADAD"));  
    }//GEN-LAST:event_FormButtonMouseExited

    private void NotificationsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotificationsMouseExited
 Notifications.setBackground(null);
            Notifications.setForeground(Color.decode("#ADADAD"));      }//GEN-LAST:event_NotificationsMouseExited


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JButton FormButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton Notifications;
    private javax.swing.JButton comment;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel n;
    // End of variables declaration//GEN-END:variables
}
