package com.saad.ClientComponents;

import com.saad.Classes.Account;
import com.saad.Classes.Car;
import java.awt.Color;


/**
 *
 * @author saadk
 */
public class deletionRequest extends javax.swing.JFrame {

    /**
     * Creates new form VisitorFrame
     */
    public deletionRequest() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        ClientCardPanel = new javax.swing.JPanel();
        j2 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, this.getLocation().y)
        );
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        setResizable(false);

        ClientCardPanel.setBackground(new java.awt.Color(51, 51, 51));
        ClientCardPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(193, 145, 0)));
        ClientCardPanel.setForeground(new java.awt.Color(51, 51, 51));
        ClientCardPanel.setMaximumSize(new java.awt.Dimension(300, 500));
        ClientCardPanel.setMinimumSize(new java.awt.Dimension(300, 500));
        ClientCardPanel.setPreferredSize(new java.awt.Dimension(300, 500));

        j2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        j2.setForeground(new java.awt.Color(255, 255, 255));
        j2.setText("Await confirmation from our team.");

        j1.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        j1.setForeground(new java.awt.Color(255, 255, 255));
        j1.setText("Account Deletion Request Submitted Successfully");

        ok.setBackground(new java.awt.Color(255, 204, 51));
        ok.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ok.setForeground(new java.awt.Color(51, 51, 51));
        ok.setText("OK");
        ok.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ok.setContentAreaFilled(false);
        ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ok.setFocusPainted(false);
        ok.setOpaque(true);
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ClientCardPanelLayout = new javax.swing.GroupLayout(ClientCardPanel);
        ClientCardPanel.setLayout(ClientCardPanelLayout);
        ClientCardPanelLayout.setHorizontalGroup(
            ClientCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientCardPanelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(ClientCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j2)
                    .addGroup(ClientCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientCardPanelLayout.createSequentialGroup()
                            .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(105, 105, 105))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClientCardPanelLayout.createSequentialGroup()
                            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)))))
        );
        ClientCardPanelLayout.setVerticalGroup(
            ClientCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientCardPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(j1)
                .addGap(18, 18, 18)
                .addComponent(j2)
                .addGap(16, 16, 16)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(ClientCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClientCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
this.setVisible(false);    }//GEN-LAST:event_okMouseClicked
        
      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deletionRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deletionRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deletionRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deletionRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deletionRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel ClientCardPanel;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
}
