/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.saad.swing;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;

/**
 *
 * @author saadk
 */
public class seperator extends javax.swing.JPanel {

    /**
     * Creates new form PanelBorder
     */
    public seperator() {
        initComponents();
         setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 5, true));
        setMaximumSize(new java.awt.Dimension(10, 32767));
        setPreferredSize(new java.awt.Dimension(10, 769));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("PanelBorder1");
    }// </editor-fold>//GEN-END:initComponents

@Override
 protected void paintChildren(Graphics grphcs) {
     Graphics2D g2 = (Graphics2D) grphcs;
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
    GradientPaint g = new GradientPaint(0, 0, Color.decode("#999999"), 0, getHeight(), Color.decode("#999999"));
    g2.setPaint(g);
g2.fillRoundRect(0, 0, getWidth(), getHeight(), 0, 0);  
    super.paintChildren(grphcs);
    }
 
 private int x;
private int y;

public void initMoving2(JFrame frame) {
    addMouseMotionListener(new MouseMotionAdapter() {
        @Override
        public void mouseDragged(MouseEvent me) {
            int newX = (me.getXOnScreen() - x) ;
            int newY = me.getYOnScreen() - y;
            frame.setLocation(newX, newY);
        }
    });
    addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent me) {
            x = me.getX();
            y = me.getY();
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
