package com.saad.swing;

import com.saad.Classes.Car;
import com.saad.ClientComponents.ClientFrame;
import com.saad.VisitorComponents.VisitorFrame;
import com.saad.main.main;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author saadk
 */
public class WelcomeFrame extends javax.swing.JPanel {

    /**
     * Creates new form WelcomeLoginFrame
     */
    public WelcomeFrame() {
        initComponents();
//                 logo.setSize(411, 55);
        
//Icon originalIcon = logo.getIcon();
//int iconWidth = originalIcon.getIconWidth();
//int iconHeight = originalIcon.getIconHeight();
//Image scaledImage = new BufferedImage(iconWidth, iconHeight, BufferedImage.TYPE_INT_ARGB);
//Graphics2D graphics = (Graphics2D) scaledImage.getGraphics();
//originalIcon.paintIcon(logo, graphics, 0, 0);
//graphics.dispose();
//scaledImage = scaledImage.getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
//logo.setIcon(new ImageIcon(scaledImage));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.saad.swing.PanelBorder();
        loginButton = new javax.swing.JButton();
        SignupButton = new javax.swing.JButton();
        VisitorButton = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        footer1 = new com.saad.GlobalComponents.Footer();

        setBackground(new java.awt.Color(53, 53, 53));
        setForeground(new java.awt.Color(53, 53, 53));
        setMaximumSize(new java.awt.Dimension(650, 743));
        setMinimumSize(new java.awt.Dimension(650, 743));
        setPreferredSize(new java.awt.Dimension(650, 743));

        panelBorder1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 51, 51)));
        panelBorder1.setMaximumSize(new java.awt.Dimension(650, 768));
        panelBorder1.setMinimumSize(new java.awt.Dimension(650, 768));
        panelBorder1.setPreferredSize(new java.awt.Dimension(650, 768));

        loginButton.setBackground(new java.awt.Color(68, 68, 68));
        loginButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(51, 51, 51));
        loginButton.setText("Login");
        loginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        loginButton.setContentAreaFilled(false);
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.setFocusPainted(false);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });

        SignupButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        SignupButton.setForeground(new java.awt.Color(51, 51, 51));
        SignupButton.setText("Sign up");
        SignupButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        SignupButton.setContentAreaFilled(false);
        SignupButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignupButton.setFocusPainted(false);
        SignupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignupButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignupButtonMouseExited(evt);
            }
        });

        VisitorButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        VisitorButton.setForeground(new java.awt.Color(68, 68, 68));
        VisitorButton.setText(" Continue as a visitor");
        VisitorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VisitorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        VisitorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisitorButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VisitorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VisitorButtonMouseExited(evt);
            }
        });

        logo.setFont(new java.awt.Font("MV Boli", 0, 77)); // NOI18N
        logo.setText("Rent Wheels");
        logo.setMaximumSize(new java.awt.Dimension(411, 55));
        logo.setMinimumSize(new java.awt.Dimension(411, 55));
        logo.setPreferredSize(new java.awt.Dimension(411, 55));

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VisitorButton)
                            .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SignupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addGap(20, 20, 20)
                .addComponent(SignupButton)
                .addGap(20, 20, 20)
                .addComponent(VisitorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );

        footer1.setPreferredSize(new java.awt.Dimension(650, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(footer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(footer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
            
            // Get the parent frame
            main thewelcomeframe = (main) SwingUtilities.getWindowAncestor(this);

            // Get the CardLayout from the main JPanel
            CardLayout cardLayout = (CardLayout) thewelcomeframe.getCardPanel().getLayout();

            // Get the panels by their names
            JPanel welcomeFrame = thewelcomeframe.getWelcomeFrame();
            JPanel welcomLoginFrame = thewelcomeframe.getWelcomeLoginFrame();

            // Set the visibility of the panels based on their names
            cardLayout.show(thewelcomeframe.getCardPanel(), "welcomeloginframe");
            welcomeFrame.setVisible(false);
            welcomLoginFrame.setVisible(true);

    }//GEN-LAST:event_loginButtonMouseClicked

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        loginButton.setForeground(Color.black);
    }//GEN-LAST:event_loginButtonMouseEntered

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseExited
        loginButton.setBackground(null);
        loginButton.setForeground(Color.decode("#333333"));
    }//GEN-LAST:event_loginButtonMouseExited

    private void SignupButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonMouseClicked
     
            // Get the parent frame
            main thewelcomeframe = (main) SwingUtilities.getWindowAncestor(this);

            // Get the CardLayout from the main JPanel
            CardLayout cardLayout = (CardLayout) thewelcomeframe.getCardPanel().getLayout();

            // Get the panels by their names
            JPanel welcomeFrame = thewelcomeframe.getWelcomeFrame();
            JPanel welcomeSignupFrame = thewelcomeframe.getWelcomeSignupFrame();

            // Set the visibility of the panels based on their names
            cardLayout.show(thewelcomeframe.getCardPanel(), "welcomeSignupFrame");
            welcomeFrame.setVisible(false);
            welcomeSignupFrame.setVisible(true);
        
    }//GEN-LAST:event_SignupButtonMouseClicked

    private void SignupButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonMouseEntered
        SignupButton.setForeground(Color.black);
    }//GEN-LAST:event_SignupButtonMouseEntered

    private void VisitorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorButtonMouseClicked
            main thewelcomeframe = (main) SwingUtilities.getWindowAncestor(this);
            thewelcomeframe.setVisible(false);
            LinkedList<Car> carList = null;
            try {
                carList = Car.listCars();
            } catch (SQLException ex) {
                System.out.println("Error while retrieving cars: " + ex.getMessage());
            }

            VisitorFrame frame = new VisitorFrame(carList);
            frame.setVisible(true);
    }//GEN-LAST:event_VisitorButtonMouseClicked

    private void VisitorButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorButtonMouseEntered
        VisitorButton.setForeground(Color.black);
    }//GEN-LAST:event_VisitorButtonMouseEntered

    private void VisitorButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorButtonMouseExited
        VisitorButton.setForeground(Color.decode("#444444"));
    }//GEN-LAST:event_VisitorButtonMouseExited

    private void SignupButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupButtonMouseExited
            SignupButton.setBackground(null);
        SignupButton.setForeground(Color.decode("#333333"));         // TODO add your handling code here:
    }//GEN-LAST:event_SignupButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignupButton;
    private javax.swing.JLabel VisitorButton;
    private com.saad.GlobalComponents.Footer footer1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logo;
    private com.saad.swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
