/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.saad.VisitorComponents;

import com.saad.ClientComponents.*;
import com.saad.main.main;
import com.saad.swing.WelcomeLoginFrame;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author saadk
 */
public class VisitorMenuItem extends javax.swing.JPanel {

    /**
     * Creates new form ClientMenuItem
     */
    public VisitorMenuItem() {
        initComponents();
                setOpaque(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        VisitorLogin = new javax.swing.JButton();
        VisitorSignup = new javax.swing.JButton();
        VisitorForm = new javax.swing.JButton();
        comments = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("MV Boli", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(199, 209, 199));
        jLabel3.setText("RentWheels");

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));

        VisitorLogin.setBackground(new java.awt.Color(255, 255, 255));
        VisitorLogin.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        VisitorLogin.setForeground(new java.awt.Color(173, 173, 173));
        VisitorLogin.setText("Log in");
        VisitorLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        VisitorLogin.setContentAreaFilled(false);
        VisitorLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VisitorLogin.setFocusPainted(false);
        VisitorLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisitorLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VisitorLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VisitorLoginMouseExited(evt);
            }
        });

        VisitorSignup.setBackground(new java.awt.Color(255, 255, 255));
        VisitorSignup.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        VisitorSignup.setForeground(new java.awt.Color(173, 173, 173));
        VisitorSignup.setText("Sign up");
        VisitorSignup.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        VisitorSignup.setContentAreaFilled(false);
        VisitorSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VisitorSignup.setFocusPainted(false);
        VisitorSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisitorSignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VisitorSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VisitorSignupMouseExited(evt);
            }
        });

        VisitorForm.setBackground(new java.awt.Color(255, 255, 255));
        VisitorForm.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        VisitorForm.setForeground(new java.awt.Color(173, 173, 173));
        VisitorForm.setText("Cars");
        VisitorForm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        VisitorForm.setContentAreaFilled(false);
        VisitorForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VisitorForm.setFocusPainted(false);
        VisitorForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisitorFormMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VisitorFormMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VisitorFormMouseExited(evt);
            }
        });

        comments.setBackground(new java.awt.Color(255, 255, 255));
        comments.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        comments.setForeground(new java.awt.Color(173, 173, 173));
        comments.setText("Comments");
        comments.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        comments.setContentAreaFilled(false);
        comments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comments.setFocusPainted(false);
        comments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                commentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                commentsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VisitorForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VisitorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(VisitorSignup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(comments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(VisitorForm)
                .addGap(55, 55, 55)
                .addComponent(comments)
                .addGap(55, 55, 55)
                .addComponent(VisitorLogin)
                .addGap(55, 55, 55)
                .addComponent(VisitorSignup)
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VisitorLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorLoginMouseExited
            VisitorLogin.setBackground(null);
            VisitorLogin.setForeground(Color.decode("#ADADAD"));
    }//GEN-LAST:event_VisitorLoginMouseExited

    private void VisitorLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorLoginMouseEntered
            VisitorLogin.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_VisitorLoginMouseEntered

    private void VisitorLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorLoginMouseClicked
            
            VisitorFrame visitorFrame = (VisitorFrame) SwingUtilities.getWindowAncestor(this);
            visitorFrame.setVisible(false);

            // Get the parent frame
            
            main m = new main ();

            // Get the CardLayout from the main JPanel
            CardLayout cardLayout = (CardLayout) m.getCardPanel().getLayout();
            m.setVisible(true);
            // Get the panels by their names
            JPanel welcomeFrame = m.getWelcomeFrame();
            JPanel welcomLoginFrame = m.getWelcomeLoginFrame();

            // Set the visibility of the panels based on their names
            cardLayout.show(m.getCardPanel(), "welcomeloginframe");
            welcomeFrame.setVisible(false);
            welcomLoginFrame.setVisible(true);
    }//GEN-LAST:event_VisitorLoginMouseClicked

    private void VisitorSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorSignupMouseEntered
            VisitorSignup.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_VisitorSignupMouseEntered

    private void VisitorFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorFormMouseClicked
              VisitorFrame vf = (VisitorFrame) SwingUtilities.getWindowAncestor(this);

        // Get the CardLayout from the main JPanel
        CardLayout cardLayout = (CardLayout) vf.getVisitorCardPanel().getLayout();

        // Get the panels by their names
        JPanel visitorCarFrameSP2 = vf.getvisitorCarFrameSP2();
        JPanel commentSP1 = vf.getcommentSP1();


        // Set the visibility of the panels based on their names
        cardLayout.show(vf.getVisitorCardPanel(), "clientFrame");
        visitorCarFrameSP2.setVisible(true);
        commentSP1.setVisible(false);

    }//GEN-LAST:event_VisitorFormMouseClicked

    private void VisitorFormMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorFormMouseEntered
            VisitorForm.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_VisitorFormMouseEntered

    private void VisitorSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorSignupMouseExited
            VisitorSignup.setBackground(null);
            VisitorSignup.setForeground(Color.decode("#ADADAD"));    }//GEN-LAST:event_VisitorSignupMouseExited

    private void VisitorFormMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorFormMouseExited
            VisitorForm.setBackground(null);
            VisitorForm.setForeground(Color.decode("#ADADAD"));    }//GEN-LAST:event_VisitorFormMouseExited

    private void VisitorSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorSignupMouseClicked
            
            VisitorFrame visitorFrame = (VisitorFrame) SwingUtilities.getWindowAncestor(this);
            visitorFrame.setVisible(false);

            // Get the parent frame
            
            main m = new main ();
            CardLayout cardLayout = (CardLayout) m.getCardPanel().getLayout();
           m.setVisible(true);
            // Get the panels by their names
            JPanel welcomeFrame = m.getWelcomeFrame();
            JPanel welcomeSignupFrame = m.getWelcomeSignupFrame();

            // Set the visibility of the panels based on their names
            cardLayout.show(m.getCardPanel(), "welcomeSignupFrame");
            welcomeFrame.setVisible(false);
            welcomeSignupFrame.setVisible(true);    }//GEN-LAST:event_VisitorSignupMouseClicked

    private void commentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentsMouseClicked
              VisitorFrame vf = (VisitorFrame) SwingUtilities.getWindowAncestor(this);

        // Get the CardLayout from the main JPanel
        CardLayout cardLayout = (CardLayout) vf.getVisitorCardPanel().getLayout();

        // Get the panels by their names
        JPanel visitorCarFrameSP2 = vf.getvisitorCarFrameSP2();
        JPanel commentSP1 = vf.getcommentSP1();


        // Set the visibility of the panels based on their names
        cardLayout.show(vf.getVisitorCardPanel(), "clientFrame");
        visitorCarFrameSP2.setVisible(false);
        commentSP1.setVisible(true);   
    }//GEN-LAST:event_commentsMouseClicked

    private void commentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentsMouseEntered
            comments.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_commentsMouseEntered

    private void commentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentsMouseExited
            comments.setBackground(null);
            comments.setForeground(Color.decode("#ADADAD"));    }//GEN-LAST:event_commentsMouseExited

@Override
 protected void paintChildren(Graphics grphcs) {
Graphics2D g2 = (Graphics2D) grphcs;
g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
super.paintChildren(grphcs);

    }
 
 private int x;
private int y;

public void initMoving2(JFrame frame) {
    addMouseMotionListener(new MouseMotionAdapter() {
        @Override
        public void mouseDragged(MouseEvent me) {
            int newX = (me.getXOnScreen() - x) ;
            int newY = me.getYOnScreen() - y;
            frame.setLocation(newX, newY);
        }
    });
    addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent me) {
            x = me.getX();
            y = me.getY();
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VisitorForm;
    private javax.swing.JButton VisitorLogin;
    private javax.swing.JButton VisitorSignup;
    private javax.swing.JButton comments;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
