/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.saad.AdminComponents;

import com.saad.ClientComponents.*;
import com.saad.Classes.Car;
import com.saad.Classes.DBConnection;
import com.saad.main.main;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author saadk
 */
public class AdminCarCard extends javax.swing.JPanel {

    private final Color backgroundColor = new Color(255,255,255); // Set the background color

    public AdminCarCard(Car car) {
        initComponents();       
        setOpaque(false);
        this.setSize(600, 450);

         setBackground(backgroundColor);
                this.setPreferredSize(new Dimension(900, 300));
                this.setMaximumSize(new Dimension(900, 300));
                this.setMinimumSize(new Dimension(900, 300));
         
         this.CarId.setText(Integer.toString(car.getRegistrationNumber()));
         this.CarId1.setText(Integer.toString(car.getRegistrationNumber()));
         this.CarName.setText(car.getModel());
         
       if (car.getAvailability().equals("Available")) {
    this.CarAvailability.setText("Unoccupied");
    this.CarAvailability.setForeground(new Color(132, 0, 0));
} else if (car.getAvailability().equals("Occupied")) {
    this.CarAvailability.setText("Occupied");
    this.CarAvailability.setForeground(new Color(0, 102, 0));
}

         this.Color.setText(car.getColor());
        this.Price.setText(Double.toString(car.getPrice()));
        byte[] imageData = getImageDataFromDatabase(car.getRegistrationNumber());
  ImageIcon imageIcon = new ImageIcon(imageData);

carpic.setSize(312, 175);
        // Resize the image to match the width and height of the 'carpic' label
        Image image = imageIcon.getImage();
    Image scaledImage = image.getScaledInstance(carpic.getWidth(), carpic.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(scaledImage);

        // Set the scaled image icon as the icon for the 'carpic' JLabel
        carpic.setIcon(scaledIcon);
        
        // Set the preferred size of the 'carpic' label to match the size of the scaled image
        carpic.setPreferredSize(new Dimension(scaledImage.getWidth(null), scaledImage.getHeight(null)));
     }

    public AdminCarCard() {
                initComponents();       
        setOpaque(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditCarButton = new javax.swing.JButton();
        carpic = new javax.swing.JLabel();
        CarAvailability = new javax.swing.JLabel();
        Color = new javax.swing.JLabel();
        RemoveCarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CarId = new javax.swing.JLabel();
        CarName = new javax.swing.JLabel();
        AvailabilityIcon = new javax.swing.JLabel();
        CarId1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(600, 350));
        setMinimumSize(new java.awt.Dimension(600, 350));
        setPreferredSize(new java.awt.Dimension(600, 350));

        EditCarButton.setBackground(new java.awt.Color(255, 255, 255));
        EditCarButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        EditCarButton.setForeground(new java.awt.Color(0, 0, 0));
        EditCarButton.setText("Edit car");
        EditCarButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 0));
        EditCarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditCarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditCarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditCarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditCarButtonMouseExited(evt);
            }
        });

        carpic.setBackground(new java.awt.Color(255, 255, 255));
        carpic.setMaximumSize(new java.awt.Dimension(312, 175));
        carpic.setMinimumSize(new java.awt.Dimension(312, 175));
        carpic.setOpaque(true);
        carpic.setPreferredSize(new java.awt.Dimension(312, 175));

        CarAvailability.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CarAvailability.setForeground(new java.awt.Color(51, 51, 51));

        Color.setBackground(new java.awt.Color(255, 255, 255));
        Color.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Color.setForeground(new java.awt.Color(255, 255, 255));
        Color.setOpaque(true);

        RemoveCarButton.setBackground(new java.awt.Color(255, 255, 255));
        RemoveCarButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RemoveCarButton.setForeground(new java.awt.Color(0, 0, 0));
        RemoveCarButton.setText("Remove car");
        RemoveCarButton.setBorder(null);
        RemoveCarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RemoveCarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveCarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RemoveCarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RemoveCarButtonMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Dh/Day");

        Price.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Price.setForeground(new java.awt.Color(51, 51, 51));
        Price.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Car Id :");

        CarId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CarId.setForeground(new java.awt.Color(255, 255, 255));

        CarName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        CarId1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CarId1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CarId1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(AvailabilityIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CarAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carpic, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CarName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CarId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveCarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditCarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CarId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(166, 166, 166)
                        .addComponent(RemoveCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(CarId1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(CarName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(carpic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Price, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CarAvailability, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addComponent(AvailabilityIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public static byte[] getImageDataFromDatabase(int carRegistrationNumber) {
    byte[] imageData = null;
    Connection connection = DBConnection.getConnection();
    String query = "SELECT picture FROM car WHERE registration_number = ?";

    try (
         PreparedStatement statement = connection.prepareStatement(query)) {
        statement.setInt(1, carRegistrationNumber);
        ResultSet resultSet = statement.executeQuery();
        if (resultSet.next()) {
            imageData = resultSet.getBytes("picture");
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }

    return imageData;
}
    
    
    private void EditCarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditCarButtonMouseEntered
        EditCarButton.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_EditCarButtonMouseEntered

    private void EditCarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditCarButtonMouseExited
        EditCarButton.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_EditCarButtonMouseExited

    private void RemoveCarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveCarButtonMouseEntered
        RemoveCarButton.setBackground(new Color(226,226,226));
    }//GEN-LAST:event_RemoveCarButtonMouseEntered

    private void RemoveCarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveCarButtonMouseExited
        RemoveCarButton.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_RemoveCarButtonMouseExited

    private void EditCarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditCarButtonMouseClicked

        try {
            Car c =null ;
            
            c = Car.findCar(Integer.parseInt(this.CarId.getText()));
            
            // Get the parent frame
            AdminFrame adminFrame = (AdminFrame) SwingUtilities.getWindowAncestor(this);

            // Get the CardLayout from the main JPanel
            CardLayout cardLayout = (CardLayout) adminFrame.getAdminCardPanel().getLayout();

            // Get the panels by their names
            JPanel addCarFrameSP1 = adminFrame.getaddCarFrameSP1();
            JPanel adminCarFrameSP1 = adminFrame.getadminCarFrameSP1();
            JPanel adminClientTable1 = adminFrame.getadminClientTable1();
            JPanel adminReservationTable1 = adminFrame.getadminReservationTable1();
            JPanel editCarFrame1 = adminFrame.geteditCarFrame1(c);
            

            // Set the visibility of the panels based on their names
            cardLayout.show(adminFrame.getAdminCardPanel(), "addCarFrameSP1");
            addCarFrameSP1.setVisible(false);
            adminClientTable1.setVisible(false);
            adminReservationTable1.setVisible(false);
            adminCarFrameSP1.setVisible(false);
            editCarFrame1.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminCarCard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EditCarButtonMouseClicked

    private void RemoveCarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveCarButtonMouseClicked
    
            int id =Integer.parseInt(this.CarId.getText());
            DeleteCarFrame dc = new DeleteCarFrame(id);
            dc.setVisible(true);

    }//GEN-LAST:event_RemoveCarButtonMouseClicked

@Override
 protected void paintChildren(Graphics grphcs) {
Graphics2D g2 = (Graphics2D) grphcs;
g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
super.paintChildren(grphcs);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvailabilityIcon;
    private javax.swing.JLabel CarAvailability;
    public javax.swing.JLabel CarId;
    public static javax.swing.JLabel CarId1;
    private javax.swing.JLabel CarName;
    private javax.swing.JLabel Color;
    private javax.swing.JButton EditCarButton;
    private javax.swing.JLabel Price;
    private javax.swing.JButton RemoveCarButton;
    private javax.swing.JLabel carpic;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
