 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.saad.AdminComponents;

import static com.saad.AdminComponents.AdminCarCard.getImageDataFromDatabase;
import com.saad.Classes.Car;
import com.saad.Classes.Comment;
import com.saad.ClientComponents.*;
import com.saad.swing.ScrollBar;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.SQLException;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class AdminFrame extends javax.swing.JFrame {

    public AdminFrame(LinkedList<Car> cars) {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
         loginHeadPanel1.initMoving(AdminFrame.this);
         
         if (cars != null) {
            for (Car car : cars) {
                AdminCarCard carCard = new AdminCarCard(car);
                AdminCarFrame.CarCardGrid.add(carCard);
            }
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        loginHeadPanel1 = new com.saad.GlobalComponents.LoginHeadPanel();
        AdminCardPanel = new javax.swing.JPanel();
        adminCarFrameSP1 = new com.saad.AdminComponents.AdminCarFrameSP();
        addCarFrameSP1 = new com.saad.AdminComponents.AddCarFrameSP();
        editCarFrame1 = new com.saad.AdminComponents.EditCarFrame();
        commentSP1 = new com.saad.AdminComponents.AdminCommentSP();
        adminReservationTable1 = new com.saad.AdminComponents.AdminReservationTable();
        adminClientsTable1 = new com.saad.AdminComponents.AdminClientsTable();
        adminMenu1 = new com.saad.AdminComponents.AdminMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1592, 815));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        loginHeadPanel1.setBackground(new java.awt.Color(137, 148, 137));
        loginHeadPanel1.setBorder(null);

        AdminCardPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(51, 51, 51)));
        AdminCardPanel.setLayout(new java.awt.CardLayout());

        adminCarFrameSP1.setMaximumSize(new java.awt.Dimension(1319, 301));
        AdminCardPanel.add(adminCarFrameSP1, "card2");
        AdminCardPanel.add(addCarFrameSP1, "card5");

        editCarFrame1.setOpaque(true);
        AdminCardPanel.add(editCarFrame1, "card6");
        AdminCardPanel.add(commentSP1, "card5");
        AdminCardPanel.add(adminReservationTable1, "card6");
        AdminCardPanel.add(adminClientsTable1, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(loginHeadPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(adminMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(AdminCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(loginHeadPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AdminCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


          LinkedList<Comment> cmtlist = Comment.getComments();
            
             if (cmtlist != null) {
                  for (Comment cmt : cmtlist) {
                      AdminCommentCard commentCard = new AdminCommentCard(cmt);
                      AdminCommentFrame.CarCardGrid.add(commentCard);
                  }
          }

    }//GEN-LAST:event_formWindowOpened

    
       public JPanel getAdminCardPanel() {
    return AdminCardPanel;
} 
    
    public JPanel getaddCarFrameSP1() {
    return addCarFrameSP1;
}
    
    public JPanel getadminCarFrameSP1() {
    return adminCarFrameSP1;
}
        public JPanel getcommentSP1() {
    return commentSP1;
}
    
    public JPanel getadminClientTable1() {
    return adminClientsTable1;
}
    
     public JPanel getadminReservationTable1() {
    return adminReservationTable1;
}   
     public JPanel geteditCarFrame1(Car c){
          
            editCarFrame1.CarModelLabel.setText((c.getModel()));

for (Enumeration<AbstractButton> buttons = editCarFrame1.buttonGroup1.getElements();
     buttons.hasMoreElements(); ) {
    AbstractButton button = buttons.nextElement();
    if (button.getText().equals(c.getColor())) {
        button.setSelected(true);
    }
}
     
            editCarFrame1.PriceLabel.setText(Integer.toString((int) c.getPrice()));
                editCarFrame1.CarIdLabel.setText(Integer.toString((int) c.getRegistrationNumber()));
            
             byte[] imageData = getImageDataFromDatabase(c.getRegistrationNumber());
  ImageIcon imageIcon = new ImageIcon(imageData);

            editCarFrame1.img.setSize(635, 350);
        // Resize the image to match the width and height of the 'carpic' label
        Image image = imageIcon.getImage();
    Image scaledImage = image.getScaledInstance(            editCarFrame1.img.getWidth(),             editCarFrame1.img.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaledIcon = new ImageIcon(scaledImage);

        // Set the scaled image icon as the icon for the 'carpic' JLabel
                    editCarFrame1.img.setIcon(scaledIcon);
        
        // Set the preferred size of the 'carpic' label to match the size of the scaled image
                    editCarFrame1.img.setPreferredSize(new Dimension(scaledImage.getWidth(null), scaledImage.getHeight(null)));


         return editCarFrame1;
     }
      public JPanel geteditCarFrame1(){
          return editCarFrame1;
     }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminCardPanel;
    private com.saad.AdminComponents.AddCarFrameSP addCarFrameSP1;
    public static com.saad.AdminComponents.AdminCarFrameSP adminCarFrameSP1;
    private com.saad.AdminComponents.AdminClientsTable adminClientsTable1;
    private com.saad.AdminComponents.AdminMenu adminMenu1;
    private com.saad.AdminComponents.AdminReservationTable adminReservationTable1;
    private com.saad.AdminComponents.AdminCommentSP commentSP1;
    private com.saad.AdminComponents.EditCarFrame editCarFrame1;
    private javax.swing.JScrollBar jScrollBar1;
    private com.saad.GlobalComponents.LoginHeadPanel loginHeadPanel1;
    // End of variables declaration//GEN-END:variables
}
