/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.saad.AdminComponents;

import chart.Charts;
import com.saad.Classes.Account;
import com.saad.ClientComponents.*;
import com.saad.VisitorComponents.VisitorFrame;
import com.saad.main.main;
import com.saad.swing.WelcomeFrame;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author saadk
 */
public class AdminMenuItem extends javax.swing.JPanel {

    /**
     * Creates new form ClientMenuItem
     */
    public AdminMenuItem() {
        initComponents();
                setOpaque(false);

    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        AddCarButton = new javax.swing.JButton();
        ReservationButton = new javax.swing.JButton();
        AdminClientsButton = new javax.swing.JButton();
        AdminFormButton = new javax.swing.JButton();
        comments = new javax.swing.JButton();
        DashBoard = new javax.swing.JButton();
        Chart = new javax.swing.JButton();
        Menu = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("MV Boli", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(199, 209, 199));
        jLabel3.setText("RentWheels");

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        setToolTipText("");

        AddCarButton.setBackground(new java.awt.Color(0, 0, 0));
        AddCarButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        AddCarButton.setForeground(new java.awt.Color(173, 173, 173));
        AddCarButton.setText("+ Add Car");
        AddCarButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        AddCarButton.setContentAreaFilled(false);
        AddCarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddCarButton.setFocusPainted(false);
        AddCarButton.setVisible(false);
        AddCarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddCarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddCarButtonMouseExited(evt);
            }
        });

        ReservationButton.setBackground(new java.awt.Color(0, 0, 0));
        ReservationButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        ReservationButton.setForeground(new java.awt.Color(173, 173, 173));
        ReservationButton.setText(" Reservations");
        ReservationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        ReservationButton.setContentAreaFilled(false);
        ReservationButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReservationButton.setFocusPainted(false);
        ReservationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservationButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReservationButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReservationButtonMouseExited(evt);
            }
        });

        AdminClientsButton.setBackground(new java.awt.Color(0, 0, 0));
        AdminClientsButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        AdminClientsButton.setForeground(new java.awt.Color(173, 173, 173));
        AdminClientsButton.setText("Clients");
        AdminClientsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        AdminClientsButton.setContentAreaFilled(false);
        AdminClientsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminClientsButton.setFocusPainted(false);
        AdminClientsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminClientsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminClientsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminClientsButtonMouseExited(evt);
            }
        });

        AdminFormButton.setBackground(new java.awt.Color(0, 0, 0));
        AdminFormButton.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        AdminFormButton.setForeground(new java.awt.Color(173, 173, 173));
        AdminFormButton.setText("Cars");
        AdminFormButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        AdminFormButton.setContentAreaFilled(false);
        AdminFormButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdminFormButton.setFocusPainted(false);
        AdminFormButton.setVisible(false);
        AdminFormButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminFormButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminFormButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminFormButtonMouseExited(evt);
            }
        });

        comments.setBackground(new java.awt.Color(0, 0, 0));
        comments.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        comments.setForeground(new java.awt.Color(173, 173, 173));
        comments.setText("Comments");
        comments.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        comments.setContentAreaFilled(false);
        comments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comments.setFocusPainted(false);
        comments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                commentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                commentsMouseExited(evt);
            }
        });

        DashBoard.setBackground(new java.awt.Color(0, 0, 0));
        DashBoard.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        DashBoard.setForeground(new java.awt.Color(173, 173, 173));
        DashBoard.setText("Dashboard");
        DashBoard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        DashBoard.setContentAreaFilled(false);
        DashBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DashBoard.setFocusPainted(false);
        DashBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashBoardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashBoardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashBoardMouseExited(evt);
            }
        });

        Chart.setBackground(new java.awt.Color(0, 0, 0));
        Chart.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        Chart.setForeground(new java.awt.Color(173, 173, 173));
        Chart.setText("Chart Insights");
        Chart.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        Chart.setContentAreaFilled(false);
        Chart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Chart.setFocusPainted(false);
        Chart.setVisible(false);
        Chart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChartMouseExited(evt);
            }
        });

        Menu.setBackground(new java.awt.Color(0, 0, 0));
        Menu.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
        Menu.setForeground(new java.awt.Color(173, 173, 173));
        Menu.setText("Menu");
        Menu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 46, 48), 0, true));
        Menu.setVisible(false);
        Menu.setContentAreaFilled(false);
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.setFocusPainted(false);
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminFormButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddCarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(DashBoard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(ReservationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(AdminClientsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(Chart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(comments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(Menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DashBoard)
                .addGap(81, 81, 81)
                .addComponent(AdminFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ReservationButton)
                .addGap(18, 18, 18)
                .addComponent(AddCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AdminClientsButton)
                .addGap(18, 18, 18)
                .addComponent(Chart, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comments)
                .addGap(163, 163, 163))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddCarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCarButtonMouseClicked
        
                    // Get the parent frame
            AdminFrame adminFrame = (AdminFrame) SwingUtilities.getWindowAncestor(this);

            // Get the CardLayout from the main JPanel
            CardLayout cardLayout = (CardLayout) adminFrame.getAdminCardPanel().getLayout();

            // Get the panels by their names
            JPanel addCarFrameSP1 = adminFrame.getaddCarFrameSP1();
            JPanel adminCarFrameSP1 = adminFrame.getadminCarFrameSP1();
            JPanel adminClientTable1 = adminFrame.getadminClientTable1();
            JPanel adminReservationTable1 = adminFrame.getadminReservationTable1();
            JPanel editCarFrame1 = adminFrame.geteditCarFrame1();
            JPanel commentSP1 = adminFrame.getcommentSP1();

            // Set the visibility of the panels based on their names
            cardLayout.show(adminFrame.getAdminCardPanel(), "addCarFrameSP1");
            addCarFrameSP1.setVisible(true);
            adminClientTable1.setVisible(false);
            adminReservationTable1.setVisible(false);
            adminCarFrameSP1.setVisible(false);
            editCarFrame1.setVisible(false);
            commentSP1.setVisible(false);
    }//GEN-LAST:event_AddCarButtonMouseClicked

    private void ReservationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationButtonMouseClicked

                            // Get the parent frame
            AdminFrame adminFrame = (AdminFrame) SwingUtilities.getWindowAncestor(this);

            // Get the CardLayout from the main JPanel
            CardLayout cardLayout = (CardLayout) adminFrame.getAdminCardPanel().getLayout();

            // Get the panels by their names
            JPanel addCarFrameSP1 = adminFrame.getaddCarFrameSP1();
            JPanel adminCarFrameSP1 = adminFrame.getadminCarFrameSP1();
            JPanel adminClientTable1 = adminFrame.getadminClientTable1();
            JPanel adminReservationTable1 = adminFrame.getadminReservationTable1();
            JPanel editCarFrame1 = adminFrame.geteditCarFrame1();
            JPanel commentSP1 = adminFrame.getcommentSP1();

            // Set the visibility of the panels based on their names
            cardLayout.show(adminFrame.getAdminCardPanel(), "addCarFrameSP1");
            addCarFrameSP1.setVisible(false);
            adminClientTable1.setVisible(false);
            adminReservationTable1.setVisible(true);
            adminCarFrameSP1.setVisible(false);
            editCarFrame1.setVisible(false);
            commentSP1.setVisible(false);
    }//GEN-LAST:event_ReservationButtonMouseClicked

    private void ReservationButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationButtonMouseExited
            ReservationButton.setBackground(null);
            ReservationButton.setForeground(Color.decode("#ADADAD"));
    }//GEN-LAST:event_ReservationButtonMouseExited

    private void AddCarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCarButtonMouseEntered
            AddCarButton.setForeground(Color.decode("#FFFFFF"));

    }//GEN-LAST:event_AddCarButtonMouseEntered

    private void ReservationButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservationButtonMouseEntered
            ReservationButton.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_ReservationButtonMouseEntered

    private void AddCarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCarButtonMouseExited
            AddCarButton.setBackground(null);
            AddCarButton.setForeground(Color.decode("#ADADAD"));    }//GEN-LAST:event_AddCarButtonMouseExited

    private void AdminClientsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminClientsButtonMouseClicked

            // Get the parent frame
            AdminFrame adminFrame = (AdminFrame) SwingUtilities.getWindowAncestor(this);

            // Get the CardLayout from the main JPanel
            CardLayout cardLayout = (CardLayout) adminFrame.getAdminCardPanel().getLayout();

            // Get the panels by their names
            JPanel addCarFrameSP1 = adminFrame.getaddCarFrameSP1();
            JPanel adminCarFrameSP1 = adminFrame.getadminCarFrameSP1();
            JPanel adminClientTable1 = adminFrame.getadminClientTable1();
            JPanel adminReservationTable1 = adminFrame.getadminReservationTable1();
            JPanel editCarFrame1 = adminFrame.geteditCarFrame1();
            JPanel commentSP1 = adminFrame.getcommentSP1();

            // Set the visibility of the panels based on their names
            cardLayout.show(adminFrame.getAdminCardPanel(), "addCarFrameSP1");
            addCarFrameSP1.setVisible(false);
            adminClientTable1.setVisible(true);
            adminReservationTable1.setVisible(false);
            adminCarFrameSP1.setVisible(false);
            editCarFrame1.setVisible(false);
            commentSP1.setVisible(false);
    }//GEN-LAST:event_AdminClientsButtonMouseClicked

    private void AdminClientsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminClientsButtonMouseEntered
            AdminClientsButton.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_AdminClientsButtonMouseEntered

    private void AdminClientsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminClientsButtonMouseExited
            AdminClientsButton.setBackground(null);
            AdminClientsButton.setForeground(Color.decode("#ADADAD"));     }//GEN-LAST:event_AdminClientsButtonMouseExited

    private void AdminFormButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminFormButtonMouseClicked

            // Get the parent frame
            AdminFrame adminFrame = (AdminFrame) SwingUtilities.getWindowAncestor(this);

            // Get the CardLayout from the main JPanel
            CardLayout cardLayout = (CardLayout) adminFrame.getAdminCardPanel().getLayout();

            // Get the panels by their names
            JPanel addCarFrameSP1 = adminFrame.getaddCarFrameSP1();
            JPanel adminCarFrameSP1 = adminFrame.getadminCarFrameSP1();
            JPanel adminClientTable1 = adminFrame.getadminClientTable1();
            JPanel adminReservationTable1 = adminFrame.getadminReservationTable1();
            JPanel editCarFrame1 = adminFrame.geteditCarFrame1();
            JPanel commentSP1 = adminFrame.getcommentSP1();

            // Set the visibility of the panels based on their names
            cardLayout.show(adminFrame.getAdminCardPanel(), "addCarFrameSP1");
            addCarFrameSP1.setVisible(false);
            adminClientTable1.setVisible(false);
            adminReservationTable1.setVisible(false);
            adminCarFrameSP1.setVisible(true);        
            editCarFrame1.setVisible(false);
            commentSP1.setVisible(false);
    }//GEN-LAST:event_AdminFormButtonMouseClicked

    private void AdminFormButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminFormButtonMouseEntered
            AdminFormButton.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_AdminFormButtonMouseEntered

    private void AdminFormButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminFormButtonMouseExited
            AdminFormButton.setBackground(null);
            AdminFormButton.setForeground(Color.decode("#ADADAD"));     }//GEN-LAST:event_AdminFormButtonMouseExited

    private void commentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentsMouseClicked

            AdminFrame adminFrame = (AdminFrame) SwingUtilities.getWindowAncestor(this);

            // Get the CardLayout from the main JPanel
            CardLayout cardLayout = (CardLayout) adminFrame.getAdminCardPanel().getLayout();

            // Get the panels by their names
            JPanel addCarFrameSP1 = adminFrame.getaddCarFrameSP1();
            JPanel adminCarFrameSP1 = adminFrame.getadminCarFrameSP1();
            JPanel adminClientTable1 = adminFrame.getadminClientTable1();
            JPanel adminReservationTable1 = adminFrame.getadminReservationTable1();
            JPanel editCarFrame1 = adminFrame.geteditCarFrame1();
            JPanel commentSP1 = adminFrame.getcommentSP1();

            // Set the visibility of the panels based on their names
            cardLayout.show(adminFrame.getAdminCardPanel(), "addCarFrameSP1");
            addCarFrameSP1.setVisible(false);
            adminClientTable1.setVisible(false);
            adminReservationTable1.setVisible(false);
            adminCarFrameSP1.setVisible(false);        
            editCarFrame1.setVisible(false);
            commentSP1.setVisible(true);
    }//GEN-LAST:event_commentsMouseClicked

    private void commentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentsMouseEntered
             comments.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_commentsMouseEntered

    private void commentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentsMouseExited
             comments.setBackground(null);
             comments.setForeground(Color.decode("#ADADAD"));    }//GEN-LAST:event_commentsMouseExited

    private void DashBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBoardMouseClicked
            
            Menu.setVisible(true);
            DashBoard.setVisible(false);
            AdminFormButton.setVisible(true);
            ReservationButton.setVisible(false);
            AddCarButton.setVisible(true);
            AdminClientsButton.setVisible(false);
            Chart.setVisible(true);
            comments.setVisible(false);
    }//GEN-LAST:event_DashBoardMouseClicked

    private void DashBoardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBoardMouseEntered
            DashBoard.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_DashBoardMouseEntered

    private void DashBoardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashBoardMouseExited
            DashBoard.setBackground(null);
            DashBoard.setForeground(Color.decode("#ADADAD"));     }//GEN-LAST:event_DashBoardMouseExited

    private void ChartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChartMouseClicked

        Charts c = new Charts();
        c.setVisible(true);

    }//GEN-LAST:event_ChartMouseClicked

    private void ChartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChartMouseEntered
            Chart.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_ChartMouseEntered

    private void ChartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChartMouseExited
            Chart.setBackground(null);
            Chart.setForeground(Color.decode("#ADADAD"));     }//GEN-LAST:event_ChartMouseExited

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked

                    Menu.setVisible(false);
            DashBoard.setVisible(true);
            AdminFormButton.setVisible(false);
            ReservationButton.setVisible(true);
            AddCarButton.setVisible(false);
            AdminClientsButton.setVisible(true);
            Chart.setVisible(false);
            comments.setVisible(true);

    }//GEN-LAST:event_MenuMouseClicked

    private void MenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseEntered
            Menu.setForeground(Color.decode("#FFFFFF"));
    }//GEN-LAST:event_MenuMouseEntered

    private void MenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseExited
            Menu.setBackground(null);
            Menu.setForeground(Color.decode("#ADADAD"));     }//GEN-LAST:event_MenuMouseExited

@Override
 protected void paintChildren(Graphics grphcs) {
Graphics2D g2 = (Graphics2D) grphcs;
g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30);
super.paintChildren(grphcs);

    }
 
 private int x;
private int y;

public void initMoving2(JFrame frame) {
    addMouseMotionListener(new MouseMotionAdapter() {
        @Override
        public void mouseDragged(MouseEvent me) {
            int newX = (me.getXOnScreen() - x) ;
            int newY = me.getYOnScreen() - y;
            frame.setLocation(newX, newY);
        }
    });
    addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent me) {
            x = me.getX();
            y = me.getY();
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCarButton;
    private javax.swing.JButton AdminClientsButton;
    private javax.swing.JButton AdminFormButton;
    private javax.swing.JButton Chart;
    private javax.swing.JButton DashBoard;
    private javax.swing.JButton Menu;
    private javax.swing.JButton ReservationButton;
    private javax.swing.JButton comments;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
