/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.saad.AdminComponents;

import com.saad.Classes.Car;
import com.saad.VisitorComponents.VisitorFrame;
import com.saad.main.main;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Window;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author saadk
 */
public class DeleteCarFrame extends javax.swing.JFrame {

    /**
     * Creates new form DeleteCarFrame
     */
    public DeleteCarFrame(int id) {
        initComponents();
        this.idc.setText(Integer.toString(id));
    }
    public DeleteCarFrame() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headPanel1 = new com.saad.GlobalComponents.HeadPanel();
        jLabel3 = new javax.swing.JLabel();
        smallPanelBorder1 = new com.saad.swing.SmallPanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        YesButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        idc = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        smallPanelBorder1.setBackground(new java.awt.Color(51, 51, 51));
        smallPanelBorder1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 204, 51)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Are you sure ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("you want to delete this vehicule ?");

        YesButton.setBackground(new java.awt.Color(255, 204, 51));
        YesButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        YesButton.setForeground(new java.awt.Color(51, 51, 51));
        YesButton.setText("Yes");
        YesButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        YesButton.setContentAreaFilled(false);
        YesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        YesButton.setFocusPainted(false);
        YesButton.setOpaque(true);
        YesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YesButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                YesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                YesButtonMouseExited(evt);
            }
        });

        CancelButton.setBackground(new java.awt.Color(255, 204, 51));
        CancelButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        CancelButton.setForeground(new java.awt.Color(51, 51, 51));
        CancelButton.setText("Cancel");
        CancelButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CancelButton.setContentAreaFilled(false);
        CancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelButton.setFocusPainted(false);
        CancelButton.setOpaque(true);
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelButtonMouseExited(evt);
            }
        });

        idc.setForeground(new java.awt.Color(60, 63, 65));

        javax.swing.GroupLayout smallPanelBorder1Layout = new javax.swing.GroupLayout(smallPanelBorder1);
        smallPanelBorder1.setLayout(smallPanelBorder1Layout);
        smallPanelBorder1Layout.setHorizontalGroup(
            smallPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallPanelBorder1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(smallPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(smallPanelBorder1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(idc)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallPanelBorder1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(YesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        smallPanelBorder1Layout.setVerticalGroup(
            smallPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(smallPanelBorder1Layout.createSequentialGroup()
                .addGroup(smallPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(smallPanelBorder1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(idc)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, smallPanelBorder1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)))
                .addGap(11, 11, 11)
                .addGroup(smallPanelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(smallPanelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smallPanelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void YesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YesButtonMouseClicked
        
        Frame[] frames = Frame.getFrames();
for (Frame frame : frames) {
    if (frame instanceof JFrame) {
        ((JFrame)frame).setVisible(false);
    }
}
        
  boolean c ;
        c = Car.deleteCar(Integer.parseInt(this.idc.getText()));
        
        if(c){
        // Get the parent frame
      LinkedList<Car> carList = null;
            try {
                carList = Car.listCars();
                 AdminFrame af2 = new AdminFrame(carList);
            af2.setVisible(true);
            } catch (SQLException ex) {
                System.out.println("Error while retrieving cars: " + ex.getMessage());
            }
        }    
    }//GEN-LAST:event_YesButtonMouseClicked

    private void YesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YesButtonMouseEntered
        YesButton.setBackground(Color.decode("#725B16"));
        YesButton.setForeground(Color.decode("#FFFFDB"));
    }//GEN-LAST:event_YesButtonMouseEntered

    private void YesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YesButtonMouseExited
        YesButton.setBackground(Color.decode("#FFCC33"));
        YesButton.setForeground(Color.decode("#333333"));
    }//GEN-LAST:event_YesButtonMouseExited

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_CancelButtonMouseClicked

    private void CancelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseEntered
        CancelButton.setBackground(Color.decode("#725B16"));
        CancelButton.setForeground(Color.decode("#FFFFDB"));    }//GEN-LAST:event_CancelButtonMouseEntered

    private void CancelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseExited
       CancelButton.setBackground(Color.decode("#FFCC33"));
        CancelButton.setForeground(Color.decode("#333333"));    }//GEN-LAST:event_CancelButtonMouseExited

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteCarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton YesButton;
    private com.saad.GlobalComponents.HeadPanel headPanel1;
    private javax.swing.JLabel idc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.saad.swing.SmallPanelBorder smallPanelBorder1;
    // End of variables declaration//GEN-END:variables
}
